allowBuilds:
  sqlite3: true
  '@scarf/scarf': true
  '@parcel/watcher': true
  '@swc/core': true
  unrs-resolver: true
  '@tailwindcss/oxide': true
  esbuild: true
  core-js: false
  core-js-pure: false

packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'

overrides:
  '@types/express': '5.0.6'
  '@types/node': '22.19.7'
